language: node_js
node_js: node
services:
- mongodb
deploy:
  api_key:
    secure: HHNB7Djj0tiVVoVTopeXoCWx4puvid2Td/Y/xLEvecmk00BDZYiAby6HZBq5VU14X743HVPNvq9Wzy3civaxdMZkHCpvT2kD8DLDAoGt+fZfnzaB7IZyESs8DaAa42zQgB99sbhA+o2m/iIiZdZmIErN8q4iYdDSIDwutV5RDy3HkJkmn45cMwWl0gfvFqR8UvmyFIj1WPQrcvQRbFWM9PyyKUuAkGbjuqqp+0PL818HbJIWIqYenQdiKMFkThLjILOm2+vR93cE6MfsComWAtX2NEL07XAYG0YXJuz7+J0JfyPL1/xTKiSNOXIKBTpDP5qX3ulA2yJFKd3X1U9+LA+sssVfl4mxuZoXE7zabXFUndrGZaUaPg+DkdyV+M40Rq2byWr78ZH7wfq1lFDrW4YJqFNr/euLZof6nqJVZYncpUS8eXCPjX7frKwd/5jbEqz2ZTWKqtF5VjCkmd3GtxcI1rfPSLahh5d0e1QJyrB1F5tq4hbo69LbK6k8UcfDmf7wlj7t32K8qWClPUrkcUYqiZNliyI3Qg77A3zsnh22pWauxZo4WW0DfHRsDg72HEepfn16h3rA40PQtTX1OdPfPQK5upt3zOTEA2jvU/FLPUNFxGihR92mK/JZy27E6Q1+d+W8XP3xTdzDRgkNE33GfRCfXW+8TuZtLAZ4/a8=
