language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  app: blog-app-live
  api_key:
    secure: rRAZqwIEmREJux6U2yS6oaxVdvYlcYha+htb+LKv/QCNE4ke0FeW+I0nYMVxf3bqtnSXdEKd8AOClLwjcVnqlcQObpw6UBrtXRt8MPajJ/CQ+bdxwlpy0vraWSN0UZJegpAO6BHnvGAltSglRuW7WWd9uU2J2RItjrCnZTkeWUrpJ6MyeQDR34LWkiHdm7uFtazVvzcu0NDK2heYManfAcS9is/LlmKPBED7rGFwuJSN9WD/s8t7W63ulFOVgp8GQ+/XHq1d/UVTU9gf07TojtV4kgPnUmbb9UJWU12CfUJfrGP5a6AJcmX9bnasgs7mMl2UfJTVSUIZF83jylapUyRBDRSL5C0OO5n8Jz/LzjxDWxdOz8tzS3t3YzMgY7TicCSJWrhVAqe43jrd1VYOj1MCYR+4t3kMbRpqM2L83a2CQ6uaJhI6ERcJ+ACUe6KAu63TH2QTY5e6bfb7yXUQJUBZ+Lkiu32/DjRP7nxQQ43Dll4dkt4rB0vE98CbfO+wI9XlE3CBtgg/DuAxZSn59132ewvpCj3gUAZ12EJQcMv2lZo0BE8cYBC2P2XfWbtiPoW07/l4WZqFXWdxD1DZ3/MOde3hmRjVComO1mkFqyCAl/DJ1Xf0VxKzYoYzxCJ2ehNMcvzcggkWtaDggUh9xhCNDKtNq19TvdolzvM9Omg=
